# Author: Dominic Contreras
# Title: Homework 3
# Class: R Shiny for Operations Management
# Date: September 27, 2018

```{r setup, include = F}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(readxl)
require(stringr)
```

```{r}
# Shapefile | U.S. States
states.load <- readOGR("tl_2018_us_state.shp", layer = "tl_2018_us_state", GDAL1_integer64_policy = TRUE)

## Clean U.S. States Data
states.load$GEOID <- gsub("^0+([1-9])","\\1", states.load$GEOID) #  Remove 0 from '01, 02, etc.
scienceDat <- read.csv("ACS_17_1YR_S1502_with_ann.csv") #  Read in % STEM info 
states.load <- states.load[states.load$GEOID %in% scienceDat$geoid,]  #  Remove U.S. territories
states.load@data <- merge(states.load@data, scienceDat, # Merge STEM info w/ Shapefile info
                          sort = FALSE, by.x = "GEOID", by.y = "geoid") 
remove(scienceDat)

# Polyline | Canada Day Parade Route
canada <- readOGR("Canada_Route.geojson")

# Pointfile | Allegheny County Polling Locations
polling <- read.csv("Allegheny_County_Polling_Place_Locations_November_2015.csv")
```

```{r}
# Percent STEM Degree by Shape (Polygon Map)
scienceBin <- stats::quantile(states.load$pctScience) #  create bin points for quantiles
sciencePal <- colorBin(c("#fef0d9","#fdcc8a","#fc8d59", #  set color pallete for map
                         "#e34a33","#b30000"), 
                       domain = states.load$pctScience, bins = scienceBin)

leaflet(data = states.load) %>% #  Create map
  addProviderTiles("Stamen.Watercolor", group = "Watercolor") %>% #  set layers
  addProviderTiles("OpenStreetMap.BlackAndWhite", group = "Black & White") %>%
  addProviderTiles("OpenTopoMap", group = "Topography") %>%
  addLayersControl( #  Layer selector (possible to add title to this box?)
    baseGroups = c("Watercolor", "Black & White", "Topography"), 
    options = layersControlOptions(collapsed = FALSE)) %>%
  addPolygons( #  Create chloropleth
    fillColor = ~sciencePal(pctScience),
    weight = 1.5,
    fillOpacity = 0.7,
    color = "black"
  ) %>%
  addLegend(position = "bottomleft", pal = sciencePal,#  Format legend
            values = states.load$pctScience, title = "Percent STEM Degree",
            labFormat = labelFormat(digits = 1, suffix = "%"))
```

```{r}
# Canada Day Parade Route 2018 - City of Grand Prairie (Line Map)
leaflet(data =canada) %>% #  Read in Canada data
  addProviderTiles("OpenStreetMap.BlackAndWhite") %>% # Set basemap
  addPolylines(color = "#FF0000") # Add + format polylines to Canada red
```

```{r}
## Allegheny County Polling Place Locations - November 2015 (Point Map)
leaflet(data = polling) %>% # Read in polling data
  addProviderTiles("Stamen.Terrain") %>% #  Set basemap
  addCircleMarkers(lng = ~X, lat = ~Y, radius = 4, #  Add circle markers 
                   color = "red", label = polling$LocName) %>%
  setView(polling$X[8], polling$Y[8], zoom = 15) # Set default zoom  
```

